k = [{'name': 'DocType Layout'},
 {'name': 'Data Import'},
 {'name': 'LDAP Settings'},
 {'name': 'Patch Log'},
 {'name': 'S3 Backup Settings'},
 {'name': 'Workspace'},
 {'name': 'Email Template'},
 {'name': 'Resignation Letter'},
 {'name': 'Help Article'},
 {'name': 'Website Settings'},
 {'name': 'Google Drive'},
 {'name': 'Company Update'},
 {'name': 'Poll Question'},
 {'name': 'Poll Question Option'},
 {'name': 'FAQ Subject'},
 {'name': 'FAQs'},
 {'name': 'FAQ Domain'},
 {'name': 'Training Course Activity'},
 {'name': 'Training Certificate'},
 {'name': 'Employee Feedback'},
 {'name': 'Training Session'},
 {'name': 'User'},
 {'name': 'Report'},
 {'name': 'Employee Training Certificate'},
 {'name': 'Job Applicant Evaluation'},
 {'name': 'Blog Post'},
 {'name': 'Customize Form'},
 {'name': 'DocType'},
 {'name': 'Email Domain'},
 {'name': 'Email Account'},
 {'name': 'Salutation'},
 {'name': 'Gender'},
 {'name': 'Country'},
 {'name': 'Role'},
 {'name': 'Dashboard Chart'},
 {'name': 'LDAP Group Mapping'},
 {'name': 'Translation'},
 {'name': 'Appraisal KPI Metrics'},
 {'name': 'System Settings'},
 {'name': 'Training Session Activity'},
 {'name': 'Letter Head'},
 {'name': 'Number Card'},
 {'name': 'Document Share Key'},
 {'name': 'Web Page'},
 {'name': 'Access Log'},
 {'name': 'Webhook Request Log'},
 {'name': 'Server Script'},
 {'name': 'DocField'},
 {'name': 'Job Candidate'},
 {'name': 'Customize Form Field'},
 {'name': 'Kanban Board'},
 {'name': 'System Console'},
 {'name': 'Variable Payout'},
 {'name': 'Employee Variable'},
 {'name': 'Newsletter'},
 {'name': 'Web Form Field'},
 {'name': 'User Permission'},
 {'name': 'Onboarding Feedback'},
 {'name': 'Training Course'},
 {'name': 'Training Subject'},
 {'name': 'Workflow State'},
 {'name': 'Event'},
 {'name': 'Notification Settings'},
 {'name': 'Web Form'},
 {'name': 'Notification Log'},
 {'name': 'Energy Point Log'},
 {'name': 'Error Snapshot'},
 {'name': 'View Log'},
 {'name': 'Web Page View'},
 {'name': 'Route History'},
 {'name': 'Error Log'},
 {'name': 'Activity Log'},
 {'name': 'Scheduled Job Log'},
 {'name': 'Language'},
 {'name': 'Network Printer Settings'},
 {'name': 'Blog Settings'},
 {'name': 'Discussion Topic'},
 {'name': 'Discussion Reply'},
 {'name': 'SMS Settings'},
 {'name': 'Tag Link'},
 {'name': 'Note'},
 {'name': 'Print Settings'},
 {'name': 'Document Naming Rule'},
 {'name': 'DocType Link'},
 {'name': 'Workflow Transition'},
 {'name': 'Assignment Rule'},
 {'name': 'Mail Merge Template'},
 {'name': 'Custom Field'},
 {'name': 'Workflow Action'},
 {'name': 'Google Settings'},
 {'name': 'Feedback'},
 {'name': 'Appraisal Interim'},
 {'name': 'Recruitment Candidate Evaluation'},
 {'name': 'Email Group'},
 {'name': 'Training Topic'},
 {'name': 'Form Tour Step'},
 {'name': 'Form Tour'},
 {'name': 'Webhook'},
 {'name': 'DocType Layout Field'},
 {'name': 'Workspace Link'},
 {'name': 'Slack Webhook URL'},
 {'name': 'Connected App'},
 {'name': 'OAuth Authorization Code'},
 {'name': 'OAuth Bearer Token'},
 {'name': 'Personal Data Deletion Step'},
 {'name': 'Personal Data Deletion Request'},
 {'name': 'Training Topic Activity'},
 {'name': 'User Group'},
 {'name': 'Training Course Topic'},
 {'name': 'User Group Member'},
 {'name': 'DocShare'},
 {'name': 'test'},
 {'name': 'Communication'},
 {'name': 'Recruitment Request'},
 {'name': 'Client Script'},
 {'name': 'User Document Type'},
 {'name': 'User Type'},
 {'name': 'Recruitment Candidate'},
 {'name': 'Contact Us Settings'},
 {'name': 'Print Format'},
 {'name': 'Auto Email Report'},
 {'name': 'User Type Module'},
 {'name': 'Website Theme'},
 {'name': 'User Select Document Type'},
 {'name': 'Test rename new'},
 {'name': 'Workspace Chart'},
 {'name': 'Workspace Shortcut'},
 {'name': 'Auto Repeat'},
 {'name': 'Module Profile'},
 {'name': 'Workflow'},
 {'name': 'Report Filter'},
 {'name': 'Custom DocPerm'},
 {'name': 'DocPerm'},
 {'name': 'Notification'},
 {'name': 'Query Parameters'},
 {'name': 'Token Cache'},
 {'name': 'Auto Repeat Day'},
 {'name': 'Event Producer Document Type'},
 {'name': 'Event Consumer Document Type'},
 {'name': 'Navbar Item'},
 {'name': 'Onboarding Step'},
 {'name': 'Currency'},
 {'name': 'Top Bar Item'},
 {'name': 'Web Template Field'},
 {'name': 'Web Template'},
 {'name': 'Event Producer Last Update'},
 {'name': 'Event Producer'},
 {'name': 'Log Settings'},
 {'name': 'Address'},
 {'name': 'About Us Settings'},
 {'name': 'Log Setting User'},
 {'name': 'Scheduled Job Type'},
 {'name': 'Social Login Key'},
 {'name': 'Assignment Rule User'},
 {'name': 'Blog Category'},
 {'name': 'Property Setter'},
 {'name': 'DocType Action'},
 {'name': 'Website Theme Ignore App'},
 {'name': 'Domain'},
 {'name': 'Has Domain'},
 {'name': 'Calendar View'},
 {'name': 'Google Contacts'},
 {'name': 'Data Migration Run'},
 {'name': 'Data Migration Plan'},
 {'name': 'Document Follow'},
 {'name': 'Website Slideshow Item'},
 {'name': 'Event Consumer'},
 {'name': 'Document Naming Rule Condition'},
 {'name': 'Event Update Log'},
 {'name': 'Report Column'},
 {'name': 'Notification Recipient'},
 {'name': 'Contact'},
 {'name': 'Console Log'},
 {'name': 'Navbar Settings'},
 {'name': 'Portal Settings'},
 {'name': 'Module Def'},
 {'name': 'Dashboard'},
 {'name': 'Email Queue'},
 {'name': 'OAuth Scope'},
 {'name': 'Event Update Log Consumer'},
 {'name': 'File'},
 {'name': 'Dashboard Chart Source'},
 {'name': 'Data Import Legacy'},
 {'name': 'Module Onboarding'},
 {'name': 'Paytm Settings'},
 {'name': 'Blogger'},
 {'name': 'List View Settings'},
 {'name': 'Installed Application'},
 {'name': 'Installed Applications'},
 {'name': 'Web Page Block'},
 {'name': 'Social Link Settings'},
 {'name': 'Onboarding Permission'},
 {'name': 'Onboarding Step Map'},
 {'name': 'Number Card Link'},
 {'name': 'Color'},
 {'name': 'OAuth Client'},
 {'name': 'User Email'},
 {'name': 'Contact Phone'},
 {'name': 'Dashboard Settings'},
 {'name': 'Document Type Field Mapping'},
 {'name': 'Dashboard Chart Link'},
 {'name': 'Prepared Report'},
 {'name': 'Dashboard Chart Field'},
 {'name': 'ToDo'},
 {'name': 'Website Route Meta'},
 {'name': 'Energy Point Rule'},
 {'name': 'Dynamic Link'},
 {'name': 'Global Search Settings'},
 {'name': 'Notification Subscribed Document'},
 {'name': 'Document Type Mapping'},
 {'name': 'Event Sync Log'},
 {'name': 'Tag'},
 {'name': 'Contact Email'},
 {'name': 'Assignment Rule Day'},
 {'name': 'Global Search DocType'},
 {'name': 'Custom Role'},
 {'name': 'List Filter'},
 {'name': 'Success Action'},
 {'name': 'Transaction Log'},
 {'name': 'Portal Menu Item'},
 {'name': 'Email Unsubscribe'},
 {'name': 'Event Participants'},
 {'name': 'Integration Request'},
 {'name': 'Comment'},
 {'name': 'Dropbox Settings'},
 {'name': 'Google Calendar'},
 {'name': 'Session Default'},
 {'name': 'Session Default Settings'},
 {'name': 'Workflow Document State'},
 {'name': 'Communication Link'},
 {'name': 'Personal Data Download Request'},
 {'name': 'Website Route Redirect'},
 {'name': 'Milestone Tracker'},
 {'name': 'Milestone'},
 {'name': 'Energy Point Settings'},
 {'name': 'Review Level'},
 {'name': 'Post'},
 {'name': 'Website Slideshow'},
 {'name': 'Website Meta Tag'},
 {'name': 'Role Permission for Page and Report'},
 {'name': 'Desktop Icon'},
 {'name': 'Post Comment'},
 {'name': 'Email Rule'},
 {'name': 'Stripe Settings'},
 {'name': 'Workflow Action Master'},
 {'name': 'Newsletter Email Group'},
 {'name': 'Version'},
 {'name': 'Data Export'},
 {'name': 'Braintree Settings'},
 {'name': 'Payment Gateway'},
 {'name': 'Domain Settings'},
 {'name': 'User Social Login'},
 {'name': 'Data Migration Connector'},
 {'name': 'Page'},
 {'name': 'Block Module'},
 {'name': 'Role Profile'},
 {'name': 'SMS Parameter'},
 {'name': 'Data Migration Mapping Detail'},
 {'name': 'Data Migration Mapping'},
 {'name': 'Data Migration Plan Mapping'},
 {'name': 'Email Flag Queue'},
 {'name': 'Unhandled Email'},
 {'name': 'Webhook Data'},
 {'name': 'Webhook Header'},
 {'name': 'Print Style'},
 {'name': 'Print Heading'},
 {'name': 'Address Template'},
 {'name': 'Email Group Member'},
 {'name': 'Has Role'},
 {'name': 'Kanban Board Column'},
 {'name': 'Website Script'},
 {'name': 'Bulk Update'},
 {'name': 'Razorpay Settings'},
 {'name': 'PayPal Settings'},
 {'name': 'OAuth Provider Settings'},
 {'name': 'Help Category'},
 {'name': 'Deleted Document'},
 {'name': 'Website Sidebar'},
 {'name': 'Website Sidebar Item'},
 {'name': 'Email Queue Recipient'},
 {'name': 'Note Seen By'},
 {'name': 'DefaultValue'},
 {'name': 'Company History'},
 {'name': 'About Us Team Member'}]

for i in k:
	if 'Redmine Integration' in i.values():
		print(i)

